server:
  port: 8083

spring:
  application:
    name: media-service
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

aws:
  credentials:
    access-key: ${ACCESS_KEY}
    secret-key: ${SECRET_KEY}
  region:
    static: ${REGION}
  s3:
    bucket: ${BUCKET_NAME}

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/